#### Importando librería Numpy


In [8]:
import numpy as np

##### Creando una lista de 10 datos


In [9]:
lista = list(range(1,11))
lista1 = [1,2,3,4,5,6,7,8,9,10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### tranformando la lista en un array

In [10]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de objeto

In [11]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de dato que contiene el arreglo


In [12]:
arreglo.dtype

dtype('int32')

##### definir como float32

In [13]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### sigue siendo un array de int32


In [14]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformar datos en float32

In [15]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#####  función similar a Range pero ocupando Arrays

In [16]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [17]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

##### ALGUNAS FUNCIONES DE NUMPY

##### Obteniendo el promedio del array

In [19]:
promedio = np.mean(arreglo)
promedio

5.5

##### Obteniendo la mediana del array

In [20]:
mediana = np.median(arreglo)
mediana

5.5

##### Desviación Estandar del Arreglo

In [21]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

##### Generación de un arreglo de 10 elementos de solo unos

In [22]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### Generación de un arreglo de 10 elementos de solo ceros

In [23]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

##### Transformando el arreglo de unos de punto flotante a enteros

In [24]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### UTILIZANDO LA FUNCIÓN RANDOM

##### Generando arreglo aleatorio de 5 elementos

In [25]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.19766653, 0.45973743, 0.32130853, 0.88344668, 0.85796672])


##### Generando una matriz aleatoria de 3x3

In [ ]:
matriz = np.random.rand(3,3)
matriz

##### Generando un arreglo aleatorio de 10 números enteros del 1 al 5

In [26]:
arreglo_aleatorio2  = np.random.randint(1,5,10)
arreglo_aleatorio2

array([4, 2, 1, 4, 2, 4, 1, 3, 1, 4])